name: Run Tests

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

env:
  JAVA_VERSION: 17

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version: ['20.x']
        os: [ubuntu-latest, windows-latest, macos-latest]
        std: [c90, c99, c11]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org/'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LLVM and set clang/clang++ on macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install llvm
          echo "CC=/opt/homebrew/opt/llvm/bin/clang" >> $GITHUB_ENV
          echo "CXX=/opt/homebrew/opt/llvm/bin/clang++" >> $GITHUB_ENV
          echo "PATH=/opt/homebrew/opt/llvm/bin:$PATH" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Run tests for std=${{ matrix.std }}
        run: npm run test:${{ matrix.std }}
